[pytest]
DJANGO_SETTINGS_MODULE = config.settings.development
python_files = tests.py test_*.py *_tests.py
addopts = --cov=accounts --cov=destinations --cov=itineraries --cov=bookings --cov=reviews --cov=budgets --cov-report=term-missing --cov-fail-under=75
