# Generated by Django 4.2.30 on 2026-09-29 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('book', 'Book'), ('cancel', 'Cancel'), ('upload', 'Upload')], help_text='Action recorded by the audit trail.', max_length=20)),
                ('model_name', models.CharField(help_text='Django model affected by the action.', max_length=100)),
                ('object_id', models.PositiveBigIntegerField(blank=True, help_text='Primary key of the affected object.', null=True)),
                ('description', models.TextField(help_text='Human-readable description of the action.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_categories', models.CharField(blank=True, default='', help_text='Comma-separated destination categories.', max_length=500)),
                ('preferred_climates', models.CharField(blank=True, default='', help_text='Comma-separated climate values.', max_length=500)),
                ('max_daily_budget', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum preferred daily destination cost.', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['user_id'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('traveler', 'Traveler'), ('admin', 'Admin')], default='traveler', help_text='Application role used for access control.', max_length=20),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active', 'role'], name='accounts_us_is_acti_c6d74b_idx'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='preferred_destinations',
            field=models.ManyToManyField(blank=True, help_text='Destinations explicitly saved by the user.', related_name='preferred_by', to='destinations.destination'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='user',
            field=models.OneToOneField(help_text='User whose travel preferences are stored.', on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User responsible for the action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', 'action'], name='accounts_ac_user_id_bfb4b4_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['model_name', 'object_id'], name='accounts_ac_model_n_91d77b_idx'),
        ),
    ]
