# Generated by Django 4.2.30 on 2026-09-29 14:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0001_initial'),
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='budget',
            name='accommodation_budget',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Budget reserved for accommodation.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='budget',
            name='activities_budget',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Budget reserved for activities.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='budget',
            name='food_budget',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Budget reserved for food.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='budget',
            name='itinerary',
            field=models.OneToOneField(help_text='Itinerary receiving this budget.', on_delete=django.db.models.deletion.CASCADE, related_name='budget_detail', to='itineraries.itinerary'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='miscellaneous_budget',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Budget reserved for miscellaneous costs.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='budget',
            name='shopping_budget',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Budget reserved for shopping.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='budget',
            name='transport_budget',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Budget reserved for transport.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Expense amount.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('accommodation', 'Accommodation'), ('activities', 'Activities'), ('food', 'Food'), ('transport', 'Transport'), ('shopping', 'Shopping'), ('miscellaneous', 'Miscellaneous')], help_text='Expense category.', max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(help_text='Date of the expense.'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(help_text='Short description of the expense.', max_length=200),
        ),
        migrations.AlterField(
            model_name='expense',
            name='itinerary',
            field=models.ForeignKey(help_text='Trip that incurred the expense.', on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='itineraries.itinerary'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional expense notes.'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='receipt',
            field=models.ImageField(blank=True, help_text='Optional receipt image.', null=True, upload_to='receipts/'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['created_at'], name='budgets_bud_created_42c3b2_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['itinerary', 'category'], name='budgets_exp_itinera_e94028_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['date'], name='budgets_exp_date_8c645b_idx'),
        ),
    ]
