# Generated by Django 4.2.30 on 2026-09-29 13:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('destinations', '0001_initial'),
        ('itineraries', '0001_initial'),
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='accommodation_type',
            field=models.CharField(choices=[('hotel', 'Hotel'), ('hostel', 'Hostel'), ('rental', 'Vacation Rental'), ('resort', 'Resort'), ('bnb', 'B&B')], help_text='Accommodation category.', max_length=10),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='address',
            field=models.CharField(help_text='Street or locality address.', max_length=300),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='amenities',
            field=models.TextField(blank=True, default='', help_text='Comma-separated amenities.'),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='contact_email',
            field=models.EmailField(help_text='Accommodation contact email.', max_length=254),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='contact_phone',
            field=models.CharField(help_text='Accommodation contact telephone.', max_length=20),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='description',
            field=models.TextField(help_text='Accommodation description.'),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='destination',
            field=models.ForeignKey(help_text='Destination where the accommodation is located.', on_delete=django.db.models.deletion.CASCADE, related_name='accommodations', to='destinations.destination'),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional accommodation photo.', null=True, upload_to='accommodations/'),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Whether the accommodation accepts bookings.'),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='max_guests',
            field=models.PositiveIntegerField(help_text='Maximum number of guests.'),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='name',
            field=models.CharField(help_text='Accommodation name.', max_length=200),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, help_text='Price for one night.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.CharField(choices=[('tour', 'Tour'), ('attraction', 'Attraction'), ('dining', 'Dining'), ('shopping', 'Shopping'), ('entertainment', 'Entertainment'), ('outdoor', 'Outdoor')], help_text='Activity category.', max_length=20),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(help_text='Activity description.'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='destination',
            field=models.ForeignKey(help_text='Destination where the activity occurs.', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='destinations.destination'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='duration_hours',
            field=models.DecimalField(decimal_places=1, help_text='Expected duration in hours.', max_digits=4),
        ),
        migrations.AlterField(
            model_name='activity',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional activity photo.', null=True, upload_to='activities/'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Whether the activity is bookable.'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='max_participants',
            field=models.PositiveIntegerField(blank=True, help_text='Optional capacity limit.', null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(help_text='Activity name.', max_length=200),
        ),
        migrations.AlterField(
            model_name='activity',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price per participant.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='activity',
            name='requirements',
            field=models.TextField(blank=True, help_text='Optional participant requirements.'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='accommodation',
            field=models.ForeignKey(blank=True, help_text='Accommodation target, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='bookings.accommodation'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='activity',
            field=models.ForeignKey(blank=True, help_text='Activity target, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='bookings.activity'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(help_text='Date of the reservation.'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='itinerary',
            field=models.ForeignKey(help_text='Trip associated with the booking.', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='itineraries.itinerary'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Total booking price.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Number of rooms, guests or activity places.'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', help_text='Booking status.', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(help_text='User who owns the booking.', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='accommodation',
            index=models.Index(fields=['is_available', 'price_per_night'], name='bookings_ac_is_avai_d8b909_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['is_available', 'price'], name='bookings_ac_is_avai_17e37d_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_date', 'status'], name='bookings_bo_booking_b730a0_idx'),
        ),
    ]
